// Bakes this package's version into a TS constant at build/test time, so a
// build with no package.json next to it (the nix flake app) still knows its
// own version. Same pattern as packages/aer-hooks.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'src', 'version.generated.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = typeof pkg.version === 'string' && pkg.version.length > 0 ? pkg.version : 'unknown';

const contents = `// GENERATED by scripts/write-version.mjs from package.json. Do not hand-edit.
export const CLI_VERSION = ${JSON.stringify(version)};
`;

// Skip the write when content matches, so an unchanged mtime never fails the
// dist-staleness check that build and test both run after this.
if (!existsSync(outPath) || readFileSync(outPath, 'utf8') !== contents) {
  writeFileSync(outPath, contents);
}
