// Bakes this package's version into a TS constant at build/test time. A
// runtime `import.meta.url`-relative package.json read broke under a
// single-file bundle (apps/cli's esbuild output collapses every module's
// url to its own, so the read landed on the CONSUMER's manifest instead).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const outPath = join(here, '..', 'src', 'version.generated.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = typeof pkg.version === 'string' && pkg.version.length > 0 ? pkg.version : 'unknown';

const contents = `// GENERATED by scripts/write-version.mjs from package.json. Do not hand-edit.
export const HOOKS_VERSION = ${JSON.stringify(version)};
`;

// Skip the write when the content already matches: both `build` and `test`
// run this as a pre-script, and a no-op rewrite would still bump the file's
// mtime past dist's, making the dist-staleness check fail on every `test`
// run right after a `build` even though nothing actually changed.
if (!existsSync(outPath) || readFileSync(outPath, 'utf8') !== contents) {
  writeFileSync(outPath, contents);
}
